### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by danielmeridew-mto** [ShaneIsrael/plex-auto-genres#24]
Plex Version 1.22.3.4523 

Followed instructions and receive API key error. 

I have successfully authenticated with username and password, and ensured that token is the same copied from end of URL string when looking at the XML of a media file from my library as per updated readme.

Process starts and appears in logs to query my media fine, but then fails:

`Invalid API key: You must be granted a valid key., when searching for entry: 21 Bridges, of type standard-movie.`

It the proceeds to fail for every media file.

**Comment by ShaneIsrael** [comment]
Are you using both Username & Password with the Token? It should just be one or the other. 

Can you give me the exact command you are running that eventually fails with the error you are seeing?

**Comment by danielmeridew-mto** [comment]
I have tried with just username and password.

Here is the command:

`python .\plex-auto-genres.py --library Movies --type standard-movie`

Here is the error I receive for each movie:

```
Invalid API key: You must be granted a valid key., when searching for entry: 107 the One Wherein There Is a Twist Pt 1, of type standard-movie.
This entry has been added to the failures.txt - once the issue is corrected in your library remove it from there and try again.
Progress: |█-------------------------------------------------| 2.1% Complete
```

Here is my .env:

```
PLEX_USERNAME="***"
PLEX_PASSWORD="***"
PLEX_SERVER_NAME="***"
PLEX_BASE_URL="http://192.168.1.1:32400"
# Text to prefix Plex collection names with
PLEX_COLLECTION_PREFIX=""
```

**Comment by ShaneIsrael** [comment]
If you are using Usename & Password auth, do not set the PLEX_BASE_URL. Leave it blank. That should solve the problem your seeing.

**Comment by danielmeridew-mto** [comment]
Thanks for coming back so quick.

I have tried as you have suggested, and Ithe following and I am still getting the same error.

I should point out that my plex server is running on a Synology NAS in case that makes any difference.

`python .\plex-auto-genres.py --library Movies --type standard-movie`

```
PLEX_USERNAME="***"
PLEX_PASSWORD="***"
PLEX_SERVER_NAME="***"
PLEX_BASE_URL=""
# Text to prefix Plex collection names with
PLEX_COLLECTION_PREFIX=""
```

```
Invalid API key: You must be granted a valid key., when searching for entry: 208 Terms of Endearment, of type standard-movie.
This entry has been added to the failures.txt - once the issue is corrected in your library remove it from there and try again.
```

**Comment by ShaneIsrael** [comment]
Interesting. Here in about an hour I'll have time to take a closer look and hopefully I can get back to you with a solution. I'd check back here in ~2 hours and I should have a response. I'm going to see if I can re-create the issue on my end.

**Comment by danielmeridew-mto** [comment]
Awesome - let me know if you need any log files!

**Comment by ShaneIsrael** [comment]
Oh that's probably not a Plex error but a TMDB error. Did you get and set a TMDB api key? You need that key for anything that is not `--type anime`. There instructions on the README page on how to get a TMDB api key.

**Comment by danielmeridew-mto** [comment]
I honestly thought it said TMDB was required for anime! Totally my mistake, thanks very much it is working now.
